easy_admin:
    entities:
#        # List the entity class name you want to manage
        Anime:
            class: App\Entity\Anime
        Episode:
            class: App\Entity\Episode
        User:
            class: App\Entity\User
            controller: App\Controller\UserAdminController